# Generated by Django 4.2.7 on 2023-12-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers'),
        ),
    ]
