# Generated by Django 4.2.7 on 2023-12-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_verificationprorequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationprorequest',
            name='user',
        ),
    ]
