# Generated by Django 4.2.7 on 2024-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='requestStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
