# Generated by Django 4.2.7 on 2024-01-06 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_premium_requeststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to=settings.AUTH_USER_MODEL),
        ),
    ]
