# Generated by Django 4.2.7 on 2023-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='userType',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='userRole',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic Student'), (2, 'Blogger'), (3, 'Premium Student')], default=1),
        ),
    ]
