# Generated by Django 4.2.7 on 2023-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_profilemodel_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
