# Generated by Django 4.2.7 on 2023-11-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_certificate_useraccount_is_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_verified_pro',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='place_of_work',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='speciality',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.certificate'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='is_verified_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfie'),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
