# Generated by Django 4.2.7 on 2023-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_useraccount_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
