# Generated by Django 4.2.7 on 2023-11-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_remove_useraccount_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.profilemodel'),
        ),
    ]
