# Generated by Django 4.2.7 on 2023-12-31 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_premiumrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='useraccount.profilemodel'),
        ),
    ]
