# Generated by Django 4.2.7 on 2023-11-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_remove_profilemodel_certificate_certificate_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
    ]
