# Generated by Django 4.2.7 on 2023-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_profilemodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='userRole',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic Dentist'), (2, 'Blogger')], default=1),
        ),
    ]
