# Generated by Django 4.2.7 on 2023-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_verified_pro',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_verified_pro',
            field=models.BooleanField(default=False),
        ),
    ]
