# Generated by Django 4.2.7 on 2023-11-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_remove_profilemodel_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='number',
            new_name='title',
        ),
    ]
