# Generated by Django 4.2.7 on 2023-11-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_profilemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='study_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
