# Generated by Django 4.2.7 on 2023-11-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_profilemodel_study_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
