# Generated by Django 4.2.7 on 2023-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
