# Generated by Django 4.2.7 on 2023-12-13 11:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
