# Generated by Django 4.2.7 on 2024-02-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postlikemodel_articlecommentlikemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentlikemodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleComment_likes', to='blog.articlecomment'),
        ),
    ]
