# Generated by Django 4.2.7 on 2023-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('blog', '0007_blog_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(related_name='categorie_posts', to='useraccount.category'),
        ),
    ]
