# Generated by Django 4.2.7 on 2023-12-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=100, null=True),
        ),
    ]
