# Generated by Django 4.2.7 on 2023-11-11 08:19

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_user_types', multiselectfield.db.fields.MultiSelectField(choices=[('basic student', 'Basic Student'), ('premium student', 'Premium Student'), ('blogger', 'Blogger')], default='basic student', max_length=100)),
                ('is_optional_for_basic', models.BooleanField(default=True)),
                ('is_optional_for_premium', models.BooleanField(default=True)),
                ('is_optional_for_doctor', models.BooleanField(default=True)),
                ('is_optional_for_admin', models.BooleanField(default=True)),
                ('exclude_users', models.ManyToManyField(blank=True, related_name='spaces_excluded', to=settings.AUTH_USER_MODEL)),
                ('include_users', models.ManyToManyField(blank=True, related_name='spaces_included', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
