# Generated by Django 4.2.7 on 2023-11-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='is_optional_for_admin',
            new_name='is_optional_for_bloggers',
        ),
        migrations.RemoveField(
            model_name='space',
            name='is_optional_for_doctor',
        ),
    ]
