# Generated by Django 4.2.7 on 2023-11-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_rename_is_optional_for_admin_space_is_optional_for_bloggers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='is_optional_for_basic',
            new_name='is_optional_for_basic_students',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='is_optional_for_premium',
            new_name='is_optional_for_premium_students',
        ),
    ]
