# Generated by Django 4.2.7 on 2024-01-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
