# Generated by Django 4.2.7 on 2023-12-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_category'),
        ('space', '0003_space_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacepost',
            name='blogPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_posts', to='blog.blogpost'),
        ),
    ]
