# Generated by Django 4.2.7 on 2023-12-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_spacepost_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacepost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
