# Generated by Django 4.2.7 on 2024-01-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_commentreply_replylike_postlike_postcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
