# Generated by Django 4.2.7 on 2024-01-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_spacepost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacepost',
            name='content',
            field=models.TextField(),
        ),
    ]
