# Generated by Django 4.2.7 on 2023-12-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_spacepost_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacepost',
            name='is_featured',
        ),
    ]
